# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Theme
ZSH_THEME="ys"

# Plugins
plugins=(archlinux common-aliases git sudo web-search)
# look into node/npm

# ZSH-Completions
plugins+=(zsh-completions)
autoload -U compinit && compinit

# User configuration
export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

export EDITOR=/usr/bin/vim

source $ZSH/oh-my-zsh.sh
